// acciones de login
export const LOGIN_START = "LOGIN_START";
export const LOGIN_CON_EXITO = "LOGIN_CON_EXITO";
export const LOGIN_CON_ERROR = "LOGIN_CON_ERROR";
export const RECUPERAR_CONTRASENA_CON_EXITO = "RECUPERAR_CONTRASENA_CON_EXITO";

// acciones de cambiar contraseña
export const ABRIR_DIALOG_CAMBIAR_CONTRASENA = "ABRIR_DIALOG_CAMBIAR_CONTRASENA";
export const CERRAR_DIALOG_CAMBIAR_CONTRASENA = "CERRAR_DIALOG_CAMBIAR_CONTRASENA";
export const CAMBIAR_CONTRASENA_START = "CAMBIAR_CONTRASENA_START";
export const CAMBIAR_CONTRASENA_CON_EXITO = "CAMBIAR_CONTRASENA_CON_EXITO";
export const CAMBIAR_CONTRASENA_CON_ERROR = "CAMBIAR_CONTRASENA_CON_ERROR";